CREATE TABLE title (
  id BIGINT(7) NOT NULL AUTO_INCREMENT,
  title VARCHAR(200),
  url VARCHAR(200),
  type VARCHAR(200),
  listTag VARCHAR(200),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));
CREATE TABLE pages (
  id BIGINT(7) NOT NULL AUTO_INCREMENT,
  type VARCHAR(200),
  kind VARCHAR(200),
  pageNum VARCHAR(200) NOT NULL,
  url VARCHAR(200) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));

CREATE TABLE tag (
  id BIGINT(7) NOT NULL AUTO_INCREMENT,
  title VARCHAR(200),
  url VARCHAR(200),
  type VARCHAR(200),
  listTag VARCHAR(200),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));

CREATE TABLE data (
  id BIGINT(7) NOT NULL AUTO_INCREMENT,
  type VARCHAR(200),
  kind VARCHAR(200),
  url VARCHAR(200),
  title VARCHAR(200),
  content VARCHAR(6200),
  magnetic VARCHAR(1000),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));
LIMIT

CREATE TABLE tagNum (
  id BIGINT(7) NOT NULL AUTO_INCREMENT,
  tag VARCHAR(200),
  pageCount VARCHAR(200),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));
